### ISSUE TITLE
OPML i/o

### ISSUE THREAD

**Issue by alexkrolick** [p-e-w/krill#1]
https://en.m.wikipedia.org/wiki/OPML

Feed readers such as Feedly and Inoreader can import and export lists of feed subscriptions in OPML format. Would be nice to be able to get that data into krill quickly using an import tool.

**Comment by sjmarshy** [comment]
:+1:

**Comment by SikhNerd** [comment]
+1

**Comment by p-e-w** [comment]
OPML import is [now supported](https://github.com/p-e-w/krill/commit/e400e1152b398137fb5f72a66853718100e25cbb) in the latest version 0.3.0!

To use it, just load a sources file with the `-S` option as usual. If the filename ends with `.opml`, krill will process it as an OPML list and import all XML URLs automagically :fireworks:

Let me know if anything doesn't work as expected.
